/* User action types */
export const SET_USER = "SET_USER";
export const CLEAR_USER = "CLEAR_USER";
export const CREATE_BOOK = "CREATE_BOOK";
export const FETCH_BOOK = "FETCH_BOOK";
export const FETCH_BOOKS = "FETCH_BOOKS";
export const UPDATE_BOOK = "UPDATE_BOOK";
export const DELETE_BOOK = "DELETE_BOOK";
export const CREATE_MEMO = "CREATE_MEMO";
export const UPDATE_READ_PAGES = "UPDATE_READ_PAGES";
export const UPDATE_BOOK_EVALUATION = "UPDATE_BOOK_EVALUATION";
export const UPDATE_BOOK_START_DATE = "UPDATE_BOOK_START_DATE";
export const UPDATE_BOOK_END_DATE = "UPDATE_BOOK_END_DATE";
export const UPDATE_BOOK_IMAGE = "UPDATE_BOOK_IMAGE";
export const FETCH_BOOK_MEMOS = "FETCH_BOOK_MEMOS";
export const UPDATE_BOOK_MEMO = "UPDATE_BOOK_MEMO";
export const DELETE_BOOK_MEMO = "DELETE_BOOK_MEMO";


